server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://60.204.156.130:3306/online_education_platform?useUnicode=true&characterEncoding=utf-8&serverTimezone
    username: root
    password: genius398
  redis:
    host: 60.204.156.130
    port: 6379
    password: genius398
    database: 0
  mail:
    host: smtp.qq.com
    port: 587
    username: 1984564067@qq.com
    password: hqnmuhzophoucaab
    from: 1984564067@qq.com
#日志
logging:
  level:
    root: info
  file:
    name: logs/application.log
    max-history: 7
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

mybatis-plus:
  #mapper配置文件
  mapper-locations: classpath:/mappers/**.xml
  #mybatis-plus日志
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    #开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#jwt
jwt:
  secret: xqs666
  expiration: 86400000


