server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://47.98.224.148:3306/online_education_platform?useUnicode=true&characterEncoding=utf-8&serverTimezone
    username: root
    password: genius398
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  redis:
    host: 47.98.224.148
    port: 6379
    password: genius398
    database: 0
  mail:
    host: smtp.qq.com
    port: 587
    username: 1984564067@qq.com
    password: hqnmuhzophoucaab
    from: 1984564067@qq.com


#日志
logging:
  level:
    root: info
  file:
    name: logs/application.log
    max-history: 7
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

mybatis-plus:
  #mapper配置文件
  mapper-locations: classpath:/mappers/**.xml
  #mybatis-plus日志
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    #开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#jwt
jwt:
  secret: xqs666
  expiration: 86400000


# application.yml

sftp:
  host: 47.98.224.148
  port: 22
  user: root
  password: 15682173858Xx
  directory: /path/to/videos/

nginx:
  video-url-prefix: http://47.98.224.148/videos/
